name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests (Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ['1.17', '1.18']
        otp: ['25', '26', '27']

    env:
      MIX_ENV: test

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{matrix.elixir}}
        otp-version: ${{matrix.otp}}
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          _build
          deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
    - name: Install and compile dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: mix do deps.get --only test, deps.compile
    - name: Check code format
      run: mix format --check-formatted
    - name: Compile code
      run: mix compile --warnings-as-errors
    - name: Run tests
      run: mix test --warnings-as-errors
